# Generated by Django 5.1.1 on 2025-09-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockCompany",
            fields=[
                (
                    "ts_code",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="TS股票代码",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="交易所代码"
                    ),
                ),
                (
                    "chairman",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="法人代表"
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="总经理"
                    ),
                ),
                (
                    "secretary",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="董秘"
                    ),
                ),
                (
                    "reg_capital",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, null=True, verbose_name="注册资本"
                    ),
                ),
                (
                    "setup_date",
                    models.DateField(blank=True, null=True, verbose_name="注册日期"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="所在省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="所在城市"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, null=True, verbose_name="公司介绍"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="公司主页"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="电子邮件"
                    ),
                ),
                (
                    "office",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="办公地址"
                    ),
                ),
                (
                    "employees",
                    models.IntegerField(blank=True, null=True, verbose_name="员工人数"),
                ),
                (
                    "main_business",
                    models.TextField(blank=True, null=True, verbose_name="主要业务及产品"),
                ),
                (
                    "business_scope",
                    models.TextField(blank=True, null=True, verbose_name="经营范围"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "上市公司基本信息",
                "verbose_name_plural": "上市公司基本信息",
                "db_table": "stock_company",
            },
        ),
        migrations.CreateModel(
            name="IndexDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts_code",
                    models.CharField(
                        db_index=True, max_length=12, verbose_name="TS指数代码"
                    ),
                ),
                ("trade_date", models.DateField(db_index=True, verbose_name="交易日期")),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="收盘点位"
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="开盘点位"
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="最高点位"
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="最低点位"
                    ),
                ),
                (
                    "pre_close",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="昨日收盘点"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True, verbose_name="涨跌点"
                    ),
                ),
                (
                    "pct_chg",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="涨跌幅"
                    ),
                ),
                ("vol", models.BigIntegerField(null=True, verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="成交额(千元)",
                    ),
                ),
            ],
            options={
                "verbose_name": "指数日线行情",
                "verbose_name_plural": "指数日线行情",
                "db_table": "index_daily",
                "ordering": ["-trade_date"],
                "indexes": [
                    models.Index(
                        fields=["ts_code", "trade_date"],
                        name="index_daily_ts_code_f4c425_idx",
                    )
                ],
                "unique_together": {("ts_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="StockBasic",
            fields=[
                (
                    "ts_code",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="TS股票代码",
                    ),
                ),
                ("symbol", models.CharField(max_length=6, verbose_name="股票代码")),
                ("name", models.CharField(max_length=20, verbose_name="股票名称")),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="地域"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="所属行业"
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="股票全称"
                    ),
                ),
                (
                    "enname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="英文全称"
                    ),
                ),
                (
                    "cnspell",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="拼音缩写"
                    ),
                ),
                (
                    "market",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="市场类型"
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="交易所代码"
                    ),
                ),
                (
                    "curr_type",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="交易货币"
                    ),
                ),
                (
                    "list_status",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="上市状态"
                    ),
                ),
                (
                    "list_date",
                    models.DateField(blank=True, null=True, verbose_name="上市日期"),
                ),
                (
                    "delist_date",
                    models.DateField(blank=True, null=True, verbose_name="退市日期"),
                ),
                (
                    "is_hs",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="是否沪深港通"
                    ),
                ),
                (
                    "act_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="实控人名称"
                    ),
                ),
                (
                    "act_ent_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="实控人企业性质"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "股票基本信息",
                "verbose_name_plural": "股票基本信息",
                "db_table": "stock_basic",
                "indexes": [
                    models.Index(
                        fields=["industry"], name="stock_basic_industr_6a8161_idx"
                    ),
                    models.Index(
                        fields=["market"], name="stock_basic_market_63832b_idx"
                    ),
                    models.Index(
                        fields=["list_status"], name="stock_basic_list_st_9ff28e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts_code",
                    models.CharField(
                        db_index=True, max_length=12, verbose_name="TS股票代码"
                    ),
                ),
                ("trade_date", models.DateField(db_index=True, verbose_name="交易日期")),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="开盘价"
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="最高价"
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="最低价"
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="收盘价"
                    ),
                ),
                (
                    "pre_close",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="昨收价"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="涨跌额"
                    ),
                ),
                (
                    "pct_chg",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, null=True, verbose_name="涨跌幅"
                    ),
                ),
                ("vol", models.BigIntegerField(null=True, verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="成交额(千元)",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "股票日线行情",
                "verbose_name_plural": "股票日线行情",
                "db_table": "stock_daily",
                "ordering": ["-trade_date"],
                "indexes": [
                    models.Index(
                        fields=["ts_code", "trade_date"],
                        name="stock_daily_ts_code_d2a1b9_idx",
                    ),
                    models.Index(
                        fields=["trade_date"], name="stock_daily_trade_d_f32b66_idx"
                    ),
                ],
                "unique_together": {("ts_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="TradeCal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exchange", models.CharField(max_length=10, verbose_name="交易所")),
                ("cal_date", models.DateField(verbose_name="日历日期")),
                ("is_open", models.BooleanField(verbose_name="是否交易")),
                (
                    "pretrade_date",
                    models.DateField(blank=True, null=True, verbose_name="上一交易日"),
                ),
            ],
            options={
                "verbose_name": "交易日历",
                "verbose_name_plural": "交易日历",
                "db_table": "trade_cal",
                "ordering": ["-cal_date"],
                "indexes": [
                    models.Index(
                        fields=["exchange", "cal_date"],
                        name="trade_cal_exchang_1cf9b2_idx",
                    ),
                    models.Index(
                        fields=["cal_date"], name="trade_cal_cal_dat_12b49f_idx"
                    ),
                ],
                "unique_together": {("exchange", "cal_date")},
            },
        ),
    ]
