"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os.path
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--t5^=7^+gm$zrlb2=d^9t5rgklea_lhx43c3!(#7d8d0$wn!4='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_jwt',
    'channels',  # WebSocket支持
    # 'django_crontab',  # 定时任务支持 - Windows系统暂时禁用
    'user.apps.UserConfig',
    'role.apps.RoleConfig',
    'chat.apps.ChatConfig',
    'stock.apps.StockConfig',
    'trading.apps.TradingConfig',
    # 'menu.apps.MenuConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS中间件必须放在最前面
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.JwtAuthenticationMiddleware',
    'user.middleware.PermissionMiddleware'
]

# CORS配置
CORS_ORIGIN_ALLOW_ALL = True  # 允许所有域名跨域访问
CORS_ALLOW_CREDENTIALS = True  # 允许携带凭证

# 允许的请求方法
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-token',
    'cache-control',
]

# 允许的响应头
CORS_EXPOSE_HEADERS = [
    'access-control-allow-origin',
    'access-control-allow-credentials',
    'cache-control',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Database - 统一数据库配置，解决跨库关联问题
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 移除数据库路由配置，使用统一数据库
# DATABASE_ROUTERS = ['utils.router.DatabaseAppsRouter']

# 移除数据库与APP的映射配置，使用统一数据库架构

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# TuShare API配置
# 请在生产环境中替换为真实的TuShare API Token
# 可以从环境变量中读取，确保安全性
TUSHARE_TOKEN = os.getenv('TUSHARE_TOKEN', 'your_tushare_token_here')

# Redis缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "mini_rabc",
        "TIMEOUT": 60 * 30,  # 默认30分钟过期
    }
}

# 市场数据缓存配置
MARKET_DATA_CACHE = {
    'CACHE_KEY': 'market_overview_data',
    'EXPIRE_TIME': 60 * 30,  # 30分钟过期
    'UPDATE_INTERVAL': 60 * 30,  # 30分钟更新间隔
}

# 定时任务配置 - Windows系统暂时禁用django-crontab
# 可使用 python market_data_cron.py 手动更新缓存
# CRONJOBS = [
#     # 每30分钟更新市场数据缓存（交易时间内更频繁）
#     ('*/30 9-11,13-15 * * 1-5', 'market_data_cron.update_market_cache', '>> /tmp/market_cache.log 2>&1'),
#     # 非交易时间每小时检查一次
#     ('0 8,12,16-23 * * 1-5', 'market_data_cron.update_market_cache', '>> /tmp/market_cache.log 2>&1'),
#     # 周末每2小时检查一次
#     ('0 */2 * * 0,6', 'market_data_cron.update_market_cache', '>> /tmp/market_cache.log 2>&1'),
# ]

# 股票数据更新频率（秒）
STOCK_DATA_REFRESH_INTERVAL = 30

# 交易相关配置
TRADING_CONFIG = {
    'MIN_SHARES': 100,  # 最小交易股数
    'COMMISSION_RATE': 0.0003,  # 手续费率
    'STAMP_TAX_RATE': 0.001,  # 印花税率（仅卖出）
    'TRANSFER_FEE_RATE': 0.00001,  # 过户费率
    'MIN_COMMISSION': 5.0,  # 最小手续费
}

# 初始资金配置
DEFAULT_INITIAL_BALANCE = 100000.00  # 默认10万初始资金

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# WebSocket (Channels) 配置
ASGI_APPLICATION = 'app.asgi.application'

# 使用内存通道层（开发环境）
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# 生产环境可以使用Redis
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }

# 定时任务配置
CRONJOBS = [
    # 每个交易日收盘后（15:10）同步当日股票数据
    ('10 15 * * 1-5', 'stock.tasks.sync_daily_stock_data', '>> /tmp/sync_stock_data.log 2>&1'),
    
    # 每个交易日收盘后（15:15）同步公司信息（每周一次）
    ('15 15 * * 1', 'stock.tasks.sync_company_info', '>> /tmp/sync_company_info.log 2>&1'),
    
    # 每天早上8点同步财经新闻
    ('0 8 * * *', 'stock.tasks.sync_financial_news', '>> /tmp/sync_news.log 2>&1'),
    
    # 每小时清理过期的WebSocket连接（可选）
    ('0 * * * *', 'stock.tasks.cleanup_websocket_connections', '>> /tmp/cleanup_ws.log 2>&1'),
]

# 定时任务时区
CRONTAB_DJANGO_SETTINGS_MODULE = 'app.settings'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

# 异步配置
ASGI_APPLICATION = 'app.asgi.application'

# JWT配置
import datetime

JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,
    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_AUTH_COOKIE': None,
}