# Generated by Django 5.1.1 on 2025-09-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStockAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=100000.0,
                        max_digits=15,
                        verbose_name="可用资金",
                    ),
                ),
                (
                    "frozen_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=15,
                        verbose_name="冻结资金",
                    ),
                ),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2,
                        default=100000.0,
                        max_digits=15,
                        verbose_name="总资产",
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=15, verbose_name="总盈亏"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_account",
                        to="user.sysuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户股票账户",
                "verbose_name_plural": "用户股票账户",
                "db_table": "user_stock_account",
            },
        ),
        migrations.CreateModel(
            name="AdminOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("STOCK_UPDATE", "更新股票信息"),
                            ("NEWS_CREATE", "创建新闻"),
                            ("NEWS_UPDATE", "更新新闻"),
                            ("NEWS_DELETE", "删除新闻"),
                            ("USER_MANAGE", "用户管理"),
                            ("TRADE_MANAGE", "交易管理"),
                            ("DATA_SYNC", "数据同步"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "operation_desc",
                    models.CharField(max_length=200, verbose_name="操作描述"),
                ),
                (
                    "target_object",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="操作对象"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="用户代理"
                    ),
                ),
                (
                    "operation_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                ("is_success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                        verbose_name="管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理员操作日志",
                "verbose_name_plural": "管理员操作日志",
                "db_table": "admin_operation_log",
                "ordering": ["-operation_time"],
                "indexes": [
                    models.Index(
                        fields=["admin_user", "operation_time"],
                        name="admin_opera_admin_u_067de5_idx",
                    ),
                    models.Index(
                        fields=["operation_type", "operation_time"],
                        name="admin_opera_operati_30ca5c_idx",
                    ),
                    models.Index(
                        fields=["operation_time"], name="admin_opera_operati_32d770_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="新闻标题")),
                ("content", models.TextField(verbose_name="新闻内容")),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="新闻来源"
                    ),
                ),
                ("publish_time", models.DateTimeField(verbose_name="发布时间")),
                ("read_count", models.IntegerField(default=0, verbose_name="阅读次数")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="新闻分类"
                    ),
                ),
                (
                    "related_stocks",
                    models.JSONField(blank=True, null=True, verbose_name="相关股票代码"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.sysuser",
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "市场新闻",
                "verbose_name_plural": "市场新闻",
                "db_table": "market_news",
                "ordering": ["-publish_time"],
                "indexes": [
                    models.Index(
                        fields=["publish_time"], name="market_news_publish_8c1cdc_idx"
                    ),
                    models.Index(
                        fields=["category"], name="market_news_categor_b09f17_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="market_news_is_publ_b12ffe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=12, verbose_name="TS股票代码")),
                ("stock_name", models.CharField(max_length=20, verbose_name="股票名称")),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "买入"), ("SELL", "卖出")],
                        max_length=4,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "trade_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="交易价格"
                    ),
                ),
                ("trade_shares", models.IntegerField(verbose_name="交易数量")),
                (
                    "trade_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="交易金额"
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=5.0, max_digits=10, verbose_name="手续费"
                    ),
                ),
                (
                    "trade_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="交易时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待成交"),
                            ("COMPLETED", "已成交"),
                            ("CANCELLED", "已撤销"),
                        ],
                        default="COMPLETED",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "交易记录",
                "verbose_name_plural": "交易记录",
                "db_table": "trade_record",
                "ordering": ["-trade_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "trade_time"],
                        name="trade_recor_user_id_6a5f6e_idx",
                    ),
                    models.Index(
                        fields=["ts_code", "trade_time"],
                        name="trade_recor_ts_code_73091a_idx",
                    ),
                    models.Index(
                        fields=["trade_time"], name="trade_recor_trade_t_60d312_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=12, verbose_name="TS股票代码")),
                ("stock_name", models.CharField(max_length=20, verbose_name="股票名称")),
                (
                    "position_shares",
                    models.IntegerField(default=0, verbose_name="持仓数量"),
                ),
                (
                    "available_shares",
                    models.IntegerField(default=0, verbose_name="可用数量"),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="成本价"
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=3, default=0, max_digits=10, verbose_name="当前价"
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="盈亏金额"
                    ),
                ),
                (
                    "profit_loss_ratio",
                    models.DecimalField(
                        decimal_places=3, default=0, max_digits=10, verbose_name="盈亏比例"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户持仓",
                "verbose_name_plural": "用户持仓",
                "db_table": "user_position",
                "indexes": [
                    models.Index(
                        fields=["user", "ts_code"],
                        name="user_positi_user_id_867199_idx",
                    ),
                    models.Index(
                        fields=["user"], name="user_positi_user_id_f69195_idx"
                    ),
                ],
                "unique_together": {("user", "ts_code")},
            },
        ),
        migrations.CreateModel(
            name="UserWatchList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(max_length=12, verbose_name="TS股票代码")),
                ("stock_name", models.CharField(max_length=20, verbose_name="股票名称")),
                (
                    "add_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.sysuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "自选股",
                "verbose_name_plural": "自选股",
                "db_table": "user_watch_list",
                "ordering": ["-add_time"],
                "indexes": [
                    models.Index(fields=["user"], name="user_watch__user_id_e7174a_idx")
                ],
                "unique_together": {("user", "ts_code")},
            },
        ),
    ]
