# Generated by Django 5.1.1 on 2025-09-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketnews",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="新闻原文链接"
            ),
        ),
        migrations.AlterField(
            model_name="adminoperationlog",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("STOCK_UPDATE", "更新股票信息"),
                    ("NEWS_CREATE", "创建新闻"),
                    ("NEWS_UPDATE", "更新新闻"),
                    ("NEWS_DELETE", "删除新闻"),
                    ("NEWS_FETCH", "爬取新闻"),
                    ("USER_MANAGE", "用户管理"),
                    ("TRADE_MANAGE", "交易管理"),
                    ("DATA_SYNC", "数据同步"),
                ],
                max_length=20,
                verbose_name="操作类型",
            ),
        ),
    ]
