# Generated by Django 5.1.1 on 2025-09-09 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstockaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_account",
                to="user.sysuser",
                verbose_name="用户",
            ),
        ),
    ]
