# Generated by Django 5.1.1 on 2025-09-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SysRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="角色名称")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="角色权限字符串"
                    ),
                ),
                ("role_sort", models.IntegerField(default=1, verbose_name="显示顺序")),
                (
                    "status",
                    models.IntegerField(default=0, verbose_name="角色状态（0正常 1停用）"),
                ),
                ("create_time", models.DateTimeField(null=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(null=True, verbose_name="更新时间")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "系统角色",
                "verbose_name_plural": "系统角色",
                "db_table": "sys_role",
            },
        ),
        migrations.CreateModel(
            name="SysUserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="role.sysrole",
                        verbose_name="角色",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="user.sysuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色关联",
                "verbose_name_plural": "用户角色关联",
                "db_table": "sys_user_role",
                "unique_together": {("user", "role")},
            },
        ),
    ]
