# Generated by Django 5.1.1 on 2025-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sysrole",
            name="create_time",
            field=models.DateTimeField(null=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="sysrole",
            name="update_time",
            field=models.DateTimeField(null=True, verbose_name="更新时间"),
        ),
    ]
